version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 30
      runas: root
